version: '3'
services:

  app:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
    volumes: ['.:/app']
    command: ["python", "app.py"]
    environment:
      - DB_HOST=db 

  db:
      image: postgres
      restart: always
      volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./sql/postal_codes.csv:/postal_codes.csv
      environment:
        POSTGRES_PASSWORD: 1234
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
      user: postgres
      ports:
      - 5432:5432
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 30s
        timeout: 10s
        retries: 3

  # mysql:
  #   image: mysql:latest
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   # healthcheck:
  #   #   test: ["CMD-SHELL", "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"]
  #   #   interval: 5s
  #   #   timeout: 5s
  #   #   retries: 3
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #   ports:
  #     - 3305:3305
  #   volumes:
  #     - ./mysql-data:/var/lib/mysql

    